#pragma once

#include "FpsComponent.h"
#include "RenderComponent.h"
#include "TextComponent.h"
#include "TransformComponent.h"
#include "PrinterComponent.h"
#include "HealthComponent.h"
#include "RemainingLivesComponent.h"
#include "PeterPepperComponent.h"
#include "DeadSignComponent.h"
#include "EnemyComponent.h"
#include "PointsDisplayComponent.h"
#include "BurgerComponent.h"
#include "PlatformComponent.h"
#include "CrossComponent.h"
#include "LevelComponent.h"